{ ... }: {

  imports = [
    flatpak/anki/default.nix
    flatpak/bottles/default.nix
    flatpak/calibre/default.nix
    flatpak/deezer/default.nix
    flatpak/element/default.nix
    flatpak/inkscape/default.nix
    flatpak/jellyfin-player/default.nix
    flatpak/kamoso/default.nix
    flatpak/libreoffice/default.nix
    flatpak/picard/default.nix
    flatpak/proton-mail/default.nix
    flatpak/protonup-qt/default.nix
    flatpak/remmina/default.nix
    flatpak/retroarch/default.nix
    flatpak/steam/default.nix
    flatpak/supersonic/default.nix
    flatpak/zoom/default.nix

    home/alacritty/default.nix
    home/atuin/default.nix
    home/atuin/default.nix
    home/awscdk/default.nix
    home/awscli/default.nix
    home/betaflight-configurator/default.nix
    home/bitwarden/default.nix
    home/browsers/default.nix
    home/darktable/default.nix
    home/drawio/default.nix
    home/fish/default.nix
    home/fontconfig/default.nix
    home/freecad/default.nix
    home/git/default.nix
    home/home-manager/default.nix
    home/k2pdfopt/default.nix
    home/kde-apps/default.nix
    home/mpv/default.nix
    home/nixvim/default.nix
    home/obsidian/default.nix
    home/obs-studio/default.nix
    home/protonmail-desktop/default.nix
    home/python3/default.nix
    home/signal-desktop/default.nix
    home/ssh/default.nix
    home/libvirtd/default.nix
    home/virt-viewer/default.nix
    home/webcord/default.nix
    home/yt-dlp/default.nix
    home/zellij/default.nix

    nixos/apache/default.nix
    nixos/bluetooth/default.nix
    nixos/bolt/default.nix
    nixos/bootloader/default.nix
    nixos/bridge/default.nix
    nixos/czkawka/default.nix
    nixos/docker/default.nix
    nixos/env/default.nix
    nixos/exit-node-routing/default.nix
    nixos/fonts/default.nix
    nixos/fwupd/default.nix
    nixos/fzf/default.nix
    nixos/grafana/default.nix
    nixos/immich/default.nix
    nixos/iperf/default.nix
    nixos/kde/default.nix
    nixos/libimobiledevice/default.nix
    nixos/libvirtd/default.nix
    nixos/localization/default.nix
    nixos/loki/default.nix
    nixos/moonstore/default.nix
    nixos/mullvad/default.nix
    nixos/networkmanager/default.nix
    nixos/nix/default.nix
    nixos/nixpkgs/default.nix
    nixos/nvidia-cuda/default.nix
    nixos/nvidia-open/default.nix
    nixos/ollama-cuda/default.nix
    nixos/podman/default.nix
    nixos/printing/default.nix
    nixos/prometheus-node-exporter/default.nix
    nixos/prometheus/default.nix
    nixos/rdfind/default.nix
    nixos/scansnap/default.nix
    nixos/sops/default.nix
    nixos/sound/default.nix
    nixos/ssh/default.nix
    nixos/sshfs/default.nix
    nixos/syncthing/default.nix
    nixos/tailscale/default.nix
    nixos/thunderbay/default.nix
    nixos/tpm/default.nix
    nixos/user/default.nix
    nixos/v4l-utils/default.nix
    nixos/zsh/default.nix
  ];
}
