# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
      kernelModules = [ "amdgpu" ];
      secrets."/swap_keyfile.bin" = "/root/swap_keyfile.bin";
      luks.devices."luks-swap" = {
        device = "/dev/disk/by-uuid/b59c205f-248e-4b54-a769-fb89e7a8f5b4";
        keyFile = "/swap_keyfile.bin";
        preLVM = false;
        allowDiscards = true;
        bypassWorkqueues = true;
      };
      luks.devices."luks-83b36ca5-9233-4848-a3e1-7ade3fefd315" = {
        device = "/dev/disk/by-uuid/83b36ca5-9233-4848-a3e1-7ade3fefd315";
        preLVM = true;
        allowDiscards = true;
        bypassWorkqueues = true;
      };
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/36f9ee72-3b73-41d1-bbe7-31a775c5bc8a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0142-78B1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    # Use the mapped swap device UUID (for /dev/mapper/swap-crypt)
    { device = "/dev/disk/by-uuid/ba7ca596-09b0-476b-9917-c11b5d98ea44"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp194s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
