{ lib, config, utils, ... }:

let
  cfg = config.mine.nfs;

  exportClients = [ "100.64.0.0/10" ];

  defaultExportOptions = export: [
    "rw"
    "sync"
    "no_subtree_check"
    "root_squash"
    "fsid=${toString export.fsid}"
  ]
  ++ lib.optional (export.sourcePath != null && export.includePaths != [ ]) "crossmnt"
  ++ lib.optional (export.mountPointGuard != null) "mp=${export.mountPointGuard}";

  defaultMountOptions = [
    "_netdev"
    "nfsvers=4.2"
    "proto=tcp"
    "hard"
    "noauto"
    "x-systemd.automount"
    "x-systemd.requires=tailscaled.service"
    "x-systemd.after=tailscaled.service"
    "x-systemd.idle-timeout=600"
    "x-systemd.device-timeout=10s"
    "x-systemd.mount-timeout=30s"
  ];

  hasExports = cfg.exports != { };
  hasMounts = cfg.mounts != { };

  tailnetServiceDeps = [ "tailscaled.service" ];

  exportBindMounts = lib.flatten (lib.mapAttrsToList
    (_: export:
      if export.sourcePath == null then
        [ ]
      else if export.includePaths == [ ] then
        [{
          source = export.sourcePath;
          target = export.path;
          inherit (export) after requires;
        }]
      else
        (map
          (path: {
            source = "${export.sourcePath}/${path}";
            target = "${export.path}/${path}";
            inherit (export) after requires;
          })
          export.includePaths)
    )
    cfg.exports);

  exportBindMountUnits = map (mount: "${utils.escapeSystemdPath mount.target}.mount") exportBindMounts;

  exportBindMountTargets = map (mount: mount.target) exportBindMounts;

  duplicateExportBindMountTargets = lib.unique (lib.filter
    (target: lib.count (candidate: candidate == target) exportBindMountTargets > 1)
    exportBindMountTargets);

  describeExportBindMountConflict = target:
    let
      conflicts = lib.filter (mount: mount.target == target) exportBindMounts;
      sources = lib.concatStringsSep ", " (map (mount: mount.source) conflicts);
    in
    "${target} is generated by multiple NFS include paths: ${sources}";
in
{
  options.mine.nfs = {
    exports = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule ({ name, ... }: {
        options = {
          path = lib.mkOption {
            type = lib.types.str;
            default = "/srv/nfs/${name}";
            description = "Local path to export over NFS.";
          };

          sourcePath = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Optional backing path used to build a curated export root with bind mounts.";
          };

          includePaths = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [ ];
            description = "Child paths from sourcePath to bind into the exported path.";
          };

          fsid = lib.mkOption {
            type = lib.types.int;
            description = "NFS filesystem ID for this export.";
          };

          mountPointGuard = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Mount point that must be mounted before this path is exported.";
          };

          after = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [ ];
            description = "Systemd units that nfs-server should start after.";
          };

          requires = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [ ];
            description = "Systemd units required by nfs-server.";
          };
        };
      }));
      default = { };
      description = "Tailnet-only NFS exports.";
    };

    mounts = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          device = lib.mkOption {
            type = lib.types.str;
            description = "NFS server and export path, for example crown:/";
          };

          mountPoint = lib.mkOption {
            type = lib.types.str;
            description = "Local mount point for the NFS export.";
          };
        };
      });
      default = { };
      description = "NFS client mounts.";
    };
  };

  config = lib.mkIf (hasExports || hasMounts) {
    assertions = [
      {
        assertion = duplicateExportBindMountTargets == [ ];
        message = ''
          NFS export includePaths generated conflicting bind mount targets:
          ${lib.concatStringsSep "\n" (map describeExportBindMountConflict duplicateExportBindMountTargets)}
        '';
      }
    ];

    boot.supportedFilesystems = [ "nfs" ];

    systemd.tmpfiles.rules =
      (lib.mapAttrsToList (_: export: "d ${export.path} 0755 root root -") cfg.exports)
      ++ (map (mount: "d ${mount.target} 0755 root root -") exportBindMounts)
      ++ (lib.mapAttrsToList (_: mount: "d ${mount.mountPoint} 0755 root root -") cfg.mounts);

    services.nfs.server = lib.mkIf hasExports {
      enable = true;
      exports = lib.concatStringsSep "\n" (lib.mapAttrsToList
        (_: export:
          let
            options = lib.concatStringsSep "," (defaultExportOptions export);
            clientSpecs = lib.concatMapStringsSep " " (client: "${client}(${options})") exportClients;
          in
          "${export.path} ${clientSpecs}"
        )
        cfg.exports);
    };

    systemd.services.nfs-server = lib.mkIf hasExports {
      after = lib.unique (tailnetServiceDeps ++ exportBindMountUnits ++ lib.flatten (lib.mapAttrsToList (_: export: export.after) cfg.exports));
      requires = lib.unique (tailnetServiceDeps ++ exportBindMountUnits ++ lib.flatten (lib.mapAttrsToList (_: export: export.requires) cfg.exports));
    };

    fileSystems =
      (lib.foldl'
        (acc: mount: acc // {
          "${mount.mountPoint}" = {
            inherit (mount) device;
            fsType = "nfs";
            options = defaultMountOptions;
          };
        })
        { }
        (lib.attrValues cfg.mounts))
      // (lib.foldl'
        (acc: mount: acc // {
          "${mount.target}" = {
            device = mount.source;
            fsType = "none";
            options = [ "bind" ]
            ++ (map (unit: "x-systemd.after=${unit}") mount.after)
            ++ (map (unit: "x-systemd.requires=${unit}") mount.requires);
          };
        })
        { }
        exportBindMounts);
  };
}
