# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.initrd.secrets."/swap_keyfile.bin" = "/root/swap_keyfile.bin";
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/02dd25fd-1b4e-458c-a672-93d8a6793312";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-58c2b99d-fc0f-4e45-a179-302f8bf02670".device = "/dev/disk/by-uuid/58c2b99d-fc0f-4e45-a179-302f8bf02670";

  boot.initrd.luks.devices."luks-swap" = {
    device = "/dev/disk/by-uuid/7c70eae0-e50a-4928-b55d-7bcd775a5de6";
    keyFile = "/swap_keyfile.bin";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5871-BFC9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/2816b186-2633-4e3c-996c-f6ea67bb8147"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp194s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
