# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      kernelModules = [ "amdgpu" ];
      secrets."/swap_keyfile.bin" = "/root/swap_keyfile.bin";
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-58c2b99d-fc0f-4e45-a179-302f8bf02670";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-58c2b99d-fc0f-4e45-a179-302f8bf02670".device = "/dev/disk/by-uuid/58c2b99d-fc0f-4e45-a179-302f8bf02670";

  boot.initrd.luks.devices."luks-swap" = {
    device = "/dev/disk/by-uuid/7c70eae0-e50a-4928-b55d-7bcd775a5de6";
    keyFile = "/swap_keyfile.bin";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5871-BFC9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/mapper/luks-swap"; }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
