{ inputs, ... }:

let
  inherit (import ./common.nix) linuxSystem;
in
{
  flake.checks.${linuxSystem} = {
    pre-commit-check = inputs.pre-commit-hooks.lib.${linuxSystem}.run {
      src = ../.;
      hooks = {
        nixpkgs-fmt.enable = true;
        statix = {
          enable = true;
          settings = {
            # git-hooks.nix's argv serializer joins list entries with literal
            # spaces into a single `--ignore X Y Z` arg, but statix only
            # accepts ONE positional after its options — so passing multiple
            # ignore paths breaks the invocation with "unexpected argument".
            # Use a single glob that matches every file we need to skip.
            # hardware-configuration.nix files are auto-generated by
            # nixos-generate-config and emit unfixable W20 "repeated keys"
            # warnings; the glob below matches both hosts.
            ignore = [ "*hardware-configuration.nix" ];
          };
        };
        deadnix = {
          enable = true;
          excludes = [ ".*hardware-configuration\\.nix$" ];
        };
        prettier.enable = true;
        black.enable = true;
        isort.enable = true;
        eslint.enable = true;
        pylint.enable = true;
      };
    };
  };
}
