# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
      kernelModules = [ ];
      luks.devices."luks-bb43ada7-1451-490c-a783-12b79ade0911".device = "/dev/disk/by-uuid/bb43ada7-1451-490c-a783-12b79ade0911";
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };


  fileSystems = {
    "/" =
      {
        device = "/dev/disk/by-uuid/4ccc8840-b037-47de-b47d-9153db65c5fa";
        fsType = "ext4";
      };

    "/boot" =
      {
        device = "/dev/disk/by-uuid/0658-3EC8";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };
  };


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
