# Generated by nixos-generate-config on the hedgehog machine.
# To regenerate after first install: nixos-generate-config --show-hardware-config
#
# Hedgehog hardware:
#   CPU:  AMD (specific model TBD)
#   GPU:  RTX 4070 Ti
#   Display: 4K 165Hz TV via HDMI/DP
#   Role: HTPC / gaming console / image generation workstation
#
# Replace this file with the actual output of nixos-generate-config.
{ lib, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # TODO: replace with actual hardware-configuration.nix from nixos-generate-config
  # Run on the target machine: nixos-generate-config --show-hardware-config
  # Then copy the output here.

  # Placeholder boot configuration — update with actual device paths after install
  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "thunderbolt" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  # Placeholder filesystem config — replace with actual UUIDs from nixos-generate-config
  # fileSystems."/" = { device = "/dev/disk/by-uuid/TODO"; fsType = "ext4"; };
  # fileSystems."/boot" = { device = "/dev/disk/by-uuid/TODO"; fsType = "vfat"; };
  # swapDevices = [ ... ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
